### PR TITLE
Added query string capability

### PR DESCRIPTION
**Pull request by RAMilewski**
Modified app.js  to support admin commands in the querystring:

?default=tagname  - subscribes the client to “tagname” instead of
“default”

?name=foo - change the name of the client to “foo”

?subscribe=tagname1, tagname2….  - Subscribes the client to a list of
one or tags.

?unsubscribe=tagname1, tagname2… - Unsubscribes the client to a list of
one or more tags.

### CODE REVIEW

**Comment by mythmon** [comment]
The changes look good to me, but the linter has some problems with it. Once those are fixed I think this is good to go.

```
$ jshint .
static/js/app.js: line 158, col 7, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 162, col 11, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 168, col 9, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 175, col 9, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 177, col 16, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 179, col 37, Expected a conditional expression and instead saw an assignment.
static/js/app.js: line 186, col 9, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 188, col 13, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 190, col 37, Expected a conditional expression and instead saw an assignment.
static/js/app.js: line 197, col 9, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
static/js/app.js: line 200, col 11, Missing semicolon.
11 errors
The command "jshint ." exited with 2.
```

**Comment by RAMilewski** [comment]
Thanks Mike!   What's the appropriate version of Javascript to write to for Corsica?  Should I not be assuming ES6?   I'm also not sure what to do about Travs CI barfing all over the code.

**Comment by RAMilewski** [comment]
Mike, can you take another look at this?  
-- Thanks!

**Comment by lonnen** [comment]
Address four very minor formatting nits and this will be good to go.

**Comment by RAMilewski** [comment]
Fixed the formatting faux-pas that Lonnen pointed out.  But I also switched to VS Code as my primary code editor.  That (or one of the extensions I loaded) also changed a bunch of formatting elsewhere.

**Comment by lonnen** [comment]
Thanks!

**Pull request merged**
