### PR TITLE
Add option to force HTTPS, for use behind SSL-terminating proxies

### LINKED ISSUE #51: Add option to redirect HTTP to HTTPS and send HSTS header
This could be achieved using something like:
https://github.com/helmetjs/helmet

This is required so that the Mozilla instance can send HSTS headers for:
https://bugzilla.mozilla.org/show_bug.cgi?id=1137035

### PR DESCRIPTION
**Pull request by mythmon**
Fixes #51

CC @edmorley

### CODE REVIEW

**Comment by edmorley** [comment]
The Travis run is failing with:
```
lib/server.js: line 18, col 32, Missing semicolon.
lib/server.js: line 65, col 88, Missing semicolon.
```

**Comment by potch** [comment]
Is this something we're looking for for our instance?

**Comment by edmorley** [comment]
Yes, see links in #51.

**Comment by mythmon** [comment]
Fixed the lint errors.

**Comment by potch** [comment]
@edmorley @mythmon commented in the relevant issue. HTTPS corsica is right now not a pleasant experience, and I don't know what the path forward is (aside from require ALL content to be HTTPS at all times)

**Comment by potch** [comment]
That said, there's nothing wrong with this changeset per se, but I don't want to be opted in to HSTS corsica myself, since most content will break.

**Comment by edmorley** [comment]
> Took a look at our current configuration and it looks like all but one of our entries works over HTTPS. If nobody's opposed, we can go update all those references to be HTTPS, and make this change viral!

Yeah I was just doing that :-) 
I'll open a PR for that regardless (there are also some HTTP 301s we can avoid too).

**Comment by edmorley** [comment]
I've opened mozilla/moz-corsica#82.

**Comment by edmorley** [comment]
Is this ready to be merged? I know we're not quite ready to enable the pref for it on the Mozilla instance, but it's off by default in this PR :-)

**Comment by edmorley** [comment]
Ping for merging :-)

**Comment by edmorley** [comment]
Many thanks :-)

**Pull request merged**
